(()=>{'use strict';
const $=s=>document.querySelector(s), canvas=$('#labCanvas'), ctx=canvas.getContext('2d');
const radius=$('#radiusRange'),pieces=$('#pieceRange'); let step=0,mode='circle',progress=1,anim=0;
let offset={x:0,y:0},drag=null,groupMove=false,answered=[false,false];
const palette=['#45c898','#61d0a5','#7bd9b4','#3ab98c','#91e2bf','#56c49a'];
const steps=[
 ['觀察圓','先觀察完整的圓與半徑 r。'],['切割圓','把圓等分成大小相同的扇形。'],
 ['展開扇形','按「展開」，觀察扇形如何離開圓心。'],['交錯排列','按「集中排列」，讓扇形一上一下交錯排列。'],
 ['找出底和高','重組圖形的底約是半個圓周，高就是半徑。'],['推導公式','把底 × 高寫成圓的面積公式。']];
function resize(){const r=canvas.parentElement.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);draw()}
function dims(){const w=canvas.clientWidth,h=canvas.clientHeight;return{w,h,cx:w*.46+offset.x,cy:h*.48+offset.y,R:Math.min(w*.23,h*.32)}}
function ease(t){return 1-Math.pow(1-t,3)}
function sector(cx,cy,R,a0,a1,fill,alpha=1){ctx.beginPath();ctx.moveTo(cx,cy);ctx.arc(cx,cy,R,a0,a1);ctx.closePath();ctx.globalAlpha=alpha;ctx.fillStyle=fill;ctx.fill();if($('#outlineToggle').checked){ctx.strokeStyle='rgba(31,44,55,.7)';ctx.lineWidth=Math.max(.35,1.1-Number(pieces.value)/260);ctx.stroke()}ctx.globalAlpha=1}
function circleScene(cut){const {cx,cy,R}=dims(),n=Number(pieces.value);if(!cut){ctx.beginPath();ctx.arc(cx,cy,R,0,Math.PI*2);ctx.fillStyle=palette[1];ctx.fill();ctx.strokeStyle='#364652';ctx.lineWidth=2;ctx.stroke()}else for(let i=0;i<n;i++){let a0=-Math.PI/2+i*2*Math.PI/n,a1=-Math.PI/2+(i+1)*2*Math.PI/n;sector(cx,cy,R,a0,a1,palette[i%palette.length])}ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(cx+R,cy);ctx.strokeStyle='#273746';ctx.lineWidth=2;ctx.stroke();label(cx+R*.5,cy-10,'r',18,800)}
function arrangement(t=1){const {w,h,cx,cy,R}=dims(),n=Number(pieces.value),half=n/2; if($('#ghostToggle').checked){ctx.globalAlpha=.14;circleScene(true);ctx.globalAlpha=1}
 const width=Math.min(w*.78,Math.PI*R),baseX=(w-width)/2+offset.x,midY=h*.5+offset.y,seg=width/half;
 for(let i=0;i<n;i++){const top=i%2===0,j=Math.floor(i/2),tx=baseX+j*seg,ty=top?midY-R:midY;const a=-Math.PI/2+i*2*Math.PI/n;const sx=cx+Math.cos(a)*R*.35,sy=cy+Math.sin(a)*R*.35;const x=sx+(tx-sx)*ease(t),y=sy+(ty-sy)*ease(t);ctx.beginPath();if(top){ctx.moveTo(x,y);ctx.lineTo(x+seg,y);ctx.lineTo(x+seg/2,y+R)}else{ctx.moveTo(x,y+R);ctx.lineTo(x+seg,y+R);ctx.lineTo(x+seg/2,y)}ctx.closePath();ctx.fillStyle=palette[top?(i%3):((i+3)%palette.length)];ctx.fill();if($('#outlineToggle').checked){ctx.strokeStyle='rgba(35,48,58,.65)';ctx.lineWidth=Math.max(.35,1.15-n/250);ctx.stroke()}}
 if(t>.92){ctx.strokeStyle='#233342';ctx.lineWidth=1.7;ctx.beginPath();ctx.moveTo(baseX,midY-R-42);ctx.lineTo(baseX+width,midY-R-42);ctx.moveTo(baseX,midY-R-50);ctx.lineTo(baseX,midY-R-34);ctx.moveTo(baseX+width,midY-R-50);ctx.lineTo(baseX+width,midY-R-34);ctx.stroke();label(baseX+width/2,midY-R-57,'底 ≈ 半個圓周 = πr',16,800);ctx.beginPath();ctx.moveTo(baseX+width+28,midY-R);ctx.lineTo(baseX+width+28,midY+R);ctx.moveTo(baseX+width+20,midY-R);ctx.lineTo(baseX+width+36,midY-R);ctx.moveTo(baseX+width+20,midY+R);ctx.lineTo(baseX+width+36,midY+R);ctx.stroke();label(baseX+width+44,midY+5,'高 = r',16,800,'left')}
 label(w/2,h-30,`等分 ${n} 份：越多份，越接近長方形`,16,800)}
function expanded(t=1){const {w,h,cx,cy,R}=dims(),n=Number(pieces.value);for(let i=0;i<n;i++){const a0=-Math.PI/2+i*2*Math.PI/n,a1=-Math.PI/2+(i+1)*2*Math.PI/n,mid=(a0+a1)/2,dist=R*.42*t;sector(cx+Math.cos(mid)*dist,cy+Math.sin(mid)*dist,R,a0,a1,palette[i%palette.length])}label(w/2,h-28,'每一片都是相同大小的扇形',16,800)}
function label(x,y,text,size=16,weight=700,align='center'){ctx.fillStyle='#182231';ctx.font=`${weight} ${size}px -apple-system,BlinkMacSystemFont,"PingFang TC",sans-serif`;ctx.textAlign=align;ctx.textBaseline='middle';ctx.fillText(text,x,y)}
function draw(){ctx.clearRect(0,0,canvas.clientWidth,canvas.clientHeight);if(mode==='circle')circleScene(false);else if(mode==='cut')circleScene(true);else if(mode==='expanded')expanded(progress);else arrangement(progress)}
function animate(to){cancelAnimationFrame(anim);const start=performance.now();progress=0;mode=to;function tick(now){progress=Math.min(1,(now-start)/700);draw();if(progress<1)anim=requestAnimationFrame(tick)}anim=requestAnimationFrame(tick)}
function setMode(m,animated=true){if(m==='arranged')animated?animate(m):(mode=m,progress=1,draw());else if(m==='expanded')animated?animate(m):(mode=m,progress=1,draw());else{mode=m;progress=1;draw()}document.querySelectorAll('.tool-btn').forEach(b=>b.classList.remove('active'));if(m==='expanded')$('#expandBtn').classList.add('active');if(m==='arranged')$('#arrangeBtn').classList.add('active')}
function updateValues(){const r=Number(radius.value),n=Number(pieces.value);$('#radiusText').value=`${r} cm`;$('#radiusText').textContent=`${r} cm`;$('#pieceText').value=`${n} 份`;$('#pieceText').textContent=`${n} 份`;$('#cVal').textContent=`${(2*Math.PI*r).toFixed(2)} cm`;$('#hcVal').textContent=`${(Math.PI*r).toFixed(2)} cm`;$('#aVal').textContent=`${(Math.PI*r*r).toFixed(2)} cm²`}
function challenge(index){const box=$('#challenge'),answers=$('#answers');box.hidden=index<4;$('#formulaPanel').hidden=step!==5||!answered[1];if(index<4)return;const final=index===5,items=final?['πr + r','2πr × r','πr × r','πr ÷ r']:['圓周長 2πr','半個圓周 πr','半徑 r','直徑 2r'],correct=final?2:1;$('#questionTitle').textContent=final?'最後一題：圓面積怎麼算？':'重組圖形的底是什麼？';$('#questionText').textContent=final?'底約是 πr，高是 r。請選出正確算式。':'上排的弧長加起來，占原來圓周長的多少？';answers.innerHTML='';$('#feedback').textContent='';items.forEach((x,i)=>{const b=document.createElement('button');b.textContent=x;b.onclick=()=>{answers.querySelectorAll('button').forEach(x=>x.classList.remove('correct','wrong'));if(i===correct){b.classList.add('correct');answered[final?1:0]=true;$('#feedback').textContent=final?'答對了！πr × r = πr²。':'答對了！上、下兩排各占半個圓周。';if(final)$('#formulaPanel').hidden=false}else{b.classList.add('wrong');$('#feedback').textContent='再觀察重組圖和原來的圓，想想每一排用了哪些扇形。'}};answers.appendChild(b)})}
function renderStep(){const [title,desc]=steps[step];$('#stepBadge').textContent=`第 ${step+1} 步 / 6`;$('#instruction').textContent=`${title}：${desc}`;$('#prevBtn').disabled=step===0;$('#nextBtn').textContent=step===5?'完成':'下一步 →';$('#stepDots').innerHTML=steps.map((_,i)=>`<i class="${i===step?'active':''}"></i>`).join('');$('#canvasTip').textContent=step<2?'拖曳圓，可以移動位置':step<4?'可用「展開／收合／集中排列」比較圖形':'觀察底、高與原來圓的關係';if(step===0)setMode('circle',false);if(step===1)setMode('cut',false);if(step===2)setMode('expanded');if(step>=3)setMode('arranged');challenge(step)}
radius.oninput=()=>{updateValues();draw()};pieces.oninput=()=>{updateValues();draw()};document.querySelectorAll('[data-pieces]').forEach(b=>b.onclick=()=>{pieces.value=b.dataset.pieces;updateValues();draw()});
$('#expandBtn').onclick=()=>setMode('expanded');$('#collapseBtn').onclick=()=>setMode(step<2?'cut':'circle');$('#arrangeBtn').onclick=()=>setMode('arranged');$('#groupBtn').onclick=()=>{groupMove=!groupMove;$('#groupBtn').classList.toggle('active',groupMove);$('#canvasTip').textContent=groupMove?'群組移動已開啟：拖曳整組圖形':'群組移動已關閉'};$('#outlineToggle').onchange=draw;$('#ghostToggle').onchange=draw;
function point(e){const r=canvas.getBoundingClientRect(),p=e.touches?e.touches[0]:e;return{x:p.clientX-r.left,y:p.clientY-r.top}}
function start(e){if(!groupMove&&step>=2)return;const p=point(e);drag={p,origin:{...offset}};canvas.setPointerCapture?.(e.pointerId);e.preventDefault()}
function move(e){if(!drag)return;const p=point(e);offset.x=drag.origin.x+p.x-drag.p.x;offset.y=drag.origin.y+p.y-drag.p.y;draw();e.preventDefault()}
function end(){drag=null}canvas.addEventListener('pointerdown',start);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',end);
$('#prevBtn').onclick=()=>{if(step>0){step--;renderStep()}};$('#nextBtn').onclick=()=>{if(step<5){step++;renderStep()}else $('#formulaPanel').hidden=false};$('#resetBtn').onclick=()=>{step=0;radius.value=5;pieces.value=24;offset={x:0,y:0};answered=[false,false];updateValues();renderStep()};
new ResizeObserver(resize).observe(canvas.parentElement);updateValues();renderStep();
})();
